"""Random binary classification prior — random hyperplanes over D features.

Each task is generated by:

  1. Sample a random hyperplane (w, b) — w ~ N(0, 1) ∈ R^D, b ~ N(0, 1).
  2. Sample feature vectors x_i ~ N(0, 1) ∈ R^D.
  3. Compute label probability via sigmoid(temperature * (w·x_i + b)),
     then flip a biased coin so labels are noisy near the decision
     boundary (temperature controls how sharp the boundary is).

The dimensionality D matches the breast-cancer benchmark (30 features)
so a model trained on this prior can be applied directly to that real
dataset without feature-shape adaptation.

The same task is then packed as a (context, query) sequence the way
the default in-context step expects:

  X[i] = (x_i[0..D-1], y_or_0, is_context_flag)     →  shape (N, D+2)
  labels = labels at query positions only           →  shape (n_query,)
  n_ctx = boundary the default step uses to slice logits

This is intentionally a *simple* prior — random linear decision
boundaries with controllable noise. TabPFN itself uses much richer
priors (Bayesian neural nets, structural causal models, mixtures).
The credibility argument here is "a PFN trained on synthetic random
linear classifiers does reasonable zero-shot classification on the
real breast-cancer dataset", not "we matched TabPFN".

Cited:
  Hollmann, Müller, Eggensperger, Hutter — "TabPFN: A Transformer That
  Solves Small Tabular Classification Problems in a Second." ICLR 2023.
  (https://arxiv.org/abs/2207.01848)
"""

from __future__ import annotations

from typing import Any

import numpy as np
from priorstudio_core import Prior, register_prior

D_FEATURES = 30  # matches sklearn.datasets.load_breast_cancer()
CTX_FRAC = 0.75
TEMPERATURE = 2.0  # sigmoid sharpness of the decision boundary


@register_prior("random_binary_classification")
class RandomBinaryClassificationPrior(Prior):
    def sample(
        self,
        *,
        seed: int,
        num_points: int = 64,
        weight_std: float = 1.0,
        bias_std: float = 1.0,
        temperature: float = TEMPERATURE,
        **_: Any,
    ) -> dict[str, Any]:
        rng = np.random.default_rng(seed)
        w = rng.normal(0.0, weight_std, size=D_FEATURES).astype(np.float32)
        b = float(rng.normal(0.0, bias_std))

        x = rng.normal(0.0, 1.0, size=(num_points, D_FEATURES)).astype(np.float32)
        logits = x @ w + b
        # Sigmoid + Bernoulli flip → labels are noisy near the boundary.
        # High temperature → sharp boundary; lower → noisier.
        p = 1.0 / (1.0 + np.exp(-temperature * logits))
        labels = (rng.uniform(0.0, 1.0, size=num_points) < p).astype(np.float32)

        # Random context/query partition per task.
        perm = rng.permutation(num_points)
        x_perm = x[perm]
        lbl_perm = labels[perm]

        n_ctx = int(num_points * CTX_FRAC)
        x_ctx, x_q = x_perm[:n_ctx], x_perm[n_ctx:]
        l_ctx, l_q = lbl_perm[:n_ctx], lbl_perm[n_ctx:]

        ctx_tok = np.concatenate(
            [
                x_ctx,
                l_ctx[:, None],
                np.ones((n_ctx, 1), dtype=np.float32),
            ],
            axis=1,
        )
        q_tok = np.concatenate(
            [
                x_q,
                np.zeros((x_q.shape[0], 1), dtype=np.float32),
                np.zeros((x_q.shape[0], 1), dtype=np.float32),
            ],
            axis=1,
        )
        seq = np.concatenate([ctx_tok, q_tok], axis=0).astype(np.float32)

        return {
            "X": seq,  # (N, D+2)
            "labels": l_q,  # (n_query,) — targets at query positions only
            "n_ctx": n_ctx,
            "w_true": w,
            "b_true": b,
        }
